# Generated by Django 2.2.13 on 2021-04-01 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='stock')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion curso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen_producto')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_venta', models.IntegerField(default=1)),
                ('direccion_envio', models.CharField(blank=True, max_length=200, null=True, verbose_name='direcion envio')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='importe')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='estado activo')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_comprador', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_venta', to='api.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Avatar')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MALE'), (1, 'FEMALE')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
